---
- name: "create wikijs directory"
  command:
    mkdir /var/wiki

- name: "download wikijs archive"
  command:
    wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz

- name: "uncompress wikijs archive"
  command:
    tar xzf wiki-js.tar.gz -C /var/wiki

- name: "Copy file with new name"
  ansible.builtin.copy:
    remote_src: true
    src: "/var/wiki/config.sample.yml"
    dest: "/var/wiki/config.yml"

- name: "Remove old file"
  ansible.builtin.file:
    path: "/var/wiki/config.sample.yml"
    state: absent

- name: "Upgrade all apt packages"
  apt:
    upgrade: yes
    update_cache: yes

- name: "Install nodejs"
  apt:
    name: nodejs
    state: present
