---
- name: Get admin password from keyvault
  shell: az keyvault secret show --name "{{ vaultsecretnameadmin }}" --vault-name "{{ vaultname }}" --query value -o tsv
  args:
    executable: /usr/bin/bash
  register: result

- name: Register ghost host with variable
  add_host:
    name: "GHOST_HOST1"
    adminpass: "{{ result.stdout }}"

- name: Get admin password from keyvault
  shell: az keyvault secret show --name "{{ vaultsecretnameuser }}" --vault-name "{{ vaultname }}" --query value -o tsv
  args:
    executable: /usr/bin/bash
  register: result


- name: Register ghost host with variable
  add_host:
    name: "GHOST_HOST2"
    userpass: "{{ result.stdout }}"