---
- name: mount module 
  hosts: app
  become: true
  vars:
    uri: "//nabsmb220.file.core.windows.net/nab-share-wikijs"
    username: "nabsmb220"
    password: "yRtJJiCCBe2N+7tdh5v9+MeC9ifccF76K4hz6xQUXy6GbNjxBF5ePslC051jpUWSwtaSnXRCTMjz+AStIz+/vA=="
    mountpoint: "/wikijsshare"
  tasks:
    - name: utility present
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: '0777'

    - name: "Mount network share"
      command:
        sudo mount -t cifs {{ uri }} /wikijsshare -o username={{ username }},password={{ password }},dir_mode=0777,file_mode=0777,serverino,nosharesock,actimeo=30