---
- set_fact: adminpass={{ hostvars['DUMMY_HOST1']['adminpass'] }}
- set_fact: userpass={{ hostvars['DUMMY_HOST2']['userpass'] }}
- name: "Install mysql-client"
  apt:
    name: mysql-client
    state: present
- name: "Use database"
  command:
      echo USE "{{ dbname }}"; | mysql -h "{{ hostdb }}" -u "{{ admindb }}" -p"{{ adminpass }}"
- name: "Give privileges to user "
  command:
      echo GRANT ALL PRIVILEGES ON "{{ dbname }}".* TO "{{ userdb }}"@'%' WITH GRANT OPTION; | mysql -h "{{ hostdb }}" -u "{{ admindb }}" -p"{{ adminpass }}"
- name: "Flush privileges"
  command:
      echo FLUSH PRIVILEGES; | mysql -h "{{ hostdb }}" -u "{{ admindb }}" -p"{{ adminpass }}"    