---
- set_fact: dbpass={{ hostvars['DUMMY_HOST']['dbpass'] }}
- name: Edit port config.yml
  ansible.builtin.lineinfile:
    path: ./wiki/config.yml
    regexp: '^port: 3000'
    line: 'port: 80'
- name: Edit db config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)type: postgres'
    replace: '\1type: mariadb'
- name: Edit host config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)host: localhost'
    replace: '\1host: {{ hostdb }}'
- name: Edit db port config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)port: 5432'
    replace: '\1port: 3306'
- name: Edit db user config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)user: wikijs'
    replace: '\1user: {{ userdb }}'
- name: Edit dbpassword config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)pass: wikijsrocks'
    replace: '\1pass: {{ dbpass }}'
- name: Edit db name config.yml
  replace:
    path: ./wiki/config.yml
    regexp: '^(\s*)db: wiki'
    replace: '\1db: {{ dbname }}'