---
- name: Create new users with passwords and assign admin privileges
  hosts: app
  become: true

  tasks:
    - name: Generate password hash for user1
      ansible.builtin.command: >
        python3 -c 'import crypt; print(crypt.crypt("{{ password_user1 }}", crypt.mksalt(crypt.METHOD_SHA512)))'
      register: hashed_password_user1
      vars:
        password_user1: "Yoloansible246" 

    - name: Generate password hash for user2
      ansible.builtin.command: >
        python3 -c 'import crypt; print(crypt.crypt("{{ password_user2 }}", crypt.mksalt(crypt.METHOD_SHA512)))'
      register: hashed_password_user2
      vars:
        password_user2: "Yoloansible642"  

    - name: Create user1
      ansible.builtin.user:
        name: samM  
        password: "{{ hashed_password_user1.stdout }}"
        state: present

    - name: Create user2
      ansible.builtin.user:
        name: nabR  
        password: "{{ hashed_password_user2.stdout }}"
        state: present

    - name: Create sudo group
      ansible.builtin.group:
        name: sudo
        state: present

    - name: Add user1 to sudo group
      ansible.builtin.user:
        name: samM  
        groups: sudo
        append: yes

    - name: Add user2 to sudo group
      ansible.builtin.user:
        name: nabR  
        groups: sudo
        append: yes







