---
- name: "Install wikijs"
  hosts: app
  become: true
  roles:
    - role: "wikijsinstall"

- name: "Get Azure info"
  hosts: localhost
  roles:
    - role: localhostinfo

- name: "Config Wiki JS"
  hosts: app
  become: true
  roles:
    - role: "wikijsconfig"

