---
vaultname: b1e3-gr4-kv-427
vaultsecretname: wikijsdbuser
tenantid: a2e466aa-4f86-4545-b5b8-97da7c8febf3
 
hostdb: b1e3-gr4-mariadb-server.mariadb.database.azure.com
userdb: wikijsdbuser@b1e3-gr4-mariadb-server
dbname: wikijs
dns: b1e3-gr4-app.westeurope.cloudapp.azure.com
